### ISSUE TITLE
Can't work with Aktualizer due to Credentials.zip does not have autoprov_credentials.p12 as expected.

### ISSUE THREAD

**Issue by Jeredriq** [uptane/ota-community-edition#2]
Uptane's website points that Aktualizer and Ota-Community-Edition can work together. And Here's documentation points out the requirements for ota client to work https://docs.ota.here.com/ota-client/latest/provisioning-methods-and-credentialszip.html.

But somehow, ota-community-edition does not generate autoprov_credentials.p12 so they cant work together anymore.

@simao I am using webapp branch and you are very responding so thats why I tagged you, also you made a commit "do not use crypt vault" maybe this issue is related to it. Any help would be greatly appreciated.

**Comment by simao** [comment]
Hi,

OTA community edition does not support auto provisioning. This is mentioned in the readme here: https://github.com/uptane/ota-community-edition#create-and-connect-a-client Only provisioning with device credentials is supported.

You might be successful using ota-lith and using device credentials https://github.com/simao/ota-lith/blob/master/docs/api-updates.md#obtain-valid-credentials 

The webapp is currently not supported by anyone as far as I know so YMMV.

**Comment by Jeredriq** [comment]
Hi again,

I've run ota-lith successfully and when I try to generate credentials.zip with `script/get-credentials.sh` it gave the following error:
```
./get-credentials.sh
+ SERVER_DIR=ota-ce-gen
+ namespace=x-ats-namespace:default
+ keyserver=keyserver.ota.ce
+ reposerver=reposerver.ota.ce
+ director=director.ota.ce
+ curl --silent --fail director.ota.ce/health
+ echo 'director.ota.ce not running'
director.ota.ce not running
+ curl --silent --fail keyserver.ota.ce/health
+ echo 'keyserver.ota.ce not running'
keyserver.ota.ce not running
+ curl --silent --fail reposerver.ota.ce/health
+ echo 'reposerver.ota.ce not running'
reposerver.ota.ce not running
+ curl -X POST reposerver.ota.ce/api/v1/user_repo '-H x-ats-namespace:default'
curl: (6) Could not resolve host: reposerver.ota.ce
```
Then I changed namespaces of keyserver, reposerver and director from sh to IPs and Ports as they have shown in Traefik dashboard, it gave the following:

```
+ SERVER_DIR=ota-ce-gen
+ namespace=x-ats-namespace:default
+ keyserver=http://172.20.0.7:7200
+ reposerver=http://172.20.0.7:7100
+ director=http://172.20.0.7:7300
+ curl --silent --fail http://172.20.0.7:7300/health
{"status":"OK"}+ curl --silent --fail http://172.20.0.7:7200/health
{"status":"OK"}+ curl --silent --fail http://172.20.0.7:7100/health
{"status":"OK"}+ curl -X POST http://172.20.0.7:7100/api/v1/user_repo '-H x-ats-namespace:default'
Illegal character ' ' in header name++ curl --fail --silent -vv http://172.20.0.7:7100/api/v1/user_repo/root.json '-H x-ats-namespace:default'
++ grep -i x-ats-tuf-repo-id
++ tr -d '\r'
++ awk '{print $3}'
+ id=
```

**Comment by simao** [comment]
Hi,

You cannot just use ips instead because the reverse proxy uses the host to proxy the request to the right service.

You need to add those hosts to your hosts file

**Comment by Jeredriq** [comment]
I've seen the following namespaces from get-credentials.sh (from ota-lith)

namespace="x-ats-namespace:default"
keyserver="keyserver.ota.ce"
reposerver="reposerver.ota.ce"
director="director.ota.ce"

Added these to hosts file (because I'm using Ota-lith now):
172.20.0.7 keyserver.ota.ce
172.20.0.7 reposerver.ota.ce
172.20.0.7 director.ota.ce

And it gave this

```
+ SERVER_DIR=ota-ce-gen
+ namespace=x-ats-namespace:default
+ keyserver=keyserver.ota.ce
+ reposerver=reposerver.ota.ce
+ director=director.ota.ce
+ curl --silent --fail director.ota.ce/health
+ echo 'director.ota.ce not running'
director.ota.ce not running
+ curl --silent --fail keyserver.ota.ce/health
+ echo 'keyserver.ota.ce not running'
keyserver.ota.ce not running
+ curl --silent --fail reposerver.ota.ce/health
+ echo 'reposerver.ota.ce not running'
reposerver.ota.ce not running
+ curl -X POST reposerver.ota.ce/api/v1/user_repo '-H x-ats-namespace:default'
curl: (7) Failed to connect to reposerver.ota.ce port 80: Connection refused
```


Also I still have these from ota-community-edition's hosts configuration in the hosts file:

192.168.59.128 app.ota.local
192.168.59.128 gateway.ota.local
192.168.59.128 treehub.ota.local
192.168.59.128 tuf-reposerver.ota.local
192.168.59.128 web-events.ota.local

**Comment by simao** [comment]
You need to use the following hosts:

```
0.0.0.0         reposerver.ota.ce
0.0.0.0         keyserver.ota.ce
0.0.0.0         director.ota.ce
0.0.0.0         treehub.ota.ce
0.0.0.0         deviceregistry.ota.ce
0.0.0.0         campaigner.ota.ce
0.0.0.0         app.ota.ce
0.0.0.0         ota.ce
```

You need to use `0.0.0.0`, traefik binds to `0.0.0.0` on port 80 and 8080 and will forward the requests to the right ip address.

**Comment by simao** [comment]
Also the error above about:

```
Illegal character ' ' in header name++ curl --fail --silent -vv http://172.20.0.7:7100/api/v1/user_repo/root.json '-H x-ats-namespace:default'
```

Seems to be some quoting issue for some shells, maybe? I updated the script on both branches and should work now.

**Comment by simao** [comment]
Sorry my comments above were for ota-lith, not community edition.

**Comment by simao** [comment]
For community edition you'll need to figure out the ip of the machine minkube is running on https://github.com/uptane/ota-community-edition#getting-started-with-minikube

**Comment by Jeredriq** [comment]
> You need to use the following hosts:
> 
> ```
> 0.0.0.0         reposerver.ota.ce
> 0.0.0.0         keyserver.ota.ce
> 0.0.0.0         director.ota.ce
> 0.0.0.0         treehub.ota.ce
> 0.0.0.0         deviceregistry.ota.ce
> 0.0.0.0         campaigner.ota.ce
> 0.0.0.0         app.ota.ce
> 0.0.0.0         ota.ce
> ```
> 
> You need to use `0.0.0.0`, traefik binds to `0.0.0.0` on port 80 and 8080 and will forward the requests to the right ip address.

Thanks a lot Simao!

I changed the IPs but all IPs listed in traefik's http services are http://172.20.0.5 so even though I change them in hosts file, I can't reach them.

**Comment by Jeredriq** [comment]
Writing the pc's external ip into hosts solved it thanks a lot!
